config/routes.rb
Rails.application.routes.draw do
  root "entries#index"

  resources :entries

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def time
    @t = Time.now
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry
    else
      render :new
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :body, :timestamps)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<h1 style="color:purple; font-family:courier;">Entries</h1>

<ul>
    <% @entries.each do |entry| %>
    <li>
        <%= link_to entry.title, entry %>
    </li>
    <% end %>
</ul>

<%= link_to "New Entry", new_entry_path %>

app/views/entries/new.html.erb
<h1 style="color:green; font-family:courier;">New Entry</h1>

<%= form_with model: @entry do |form|%>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% @entry.errors.full_messages_for(:title).each do |message|%>
        <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body%>
        <% @entry.errors.full_messages_for(:body).each do |message|%>
        <div><%= message %></div>
        <% end %>

    </div>

    <div id="word_count_container">
        <h4 style="color:green; font-family:courier;"> Word Count: <span id="word_count">0</span> </h4>
    </div>

    <div>
        <%= form.submit %>
    </div>
    

    <% end %>

    <script type="text/javascript"> 

        var count = document.getElementById('word_count');
        var input = document.getElementById('entry_body');

        input.addEventListener('keyup', wordCounter())

        function wordCounter() {
            console.log("Hello ouch");
            var text = input.value;
            var wordCount = 0;
            for (var i = 0; i <= text.length; i++){

                if (text[i] == ' '){
        
                    wordCount++;
                }
            }
            count.innerText = wordCount;
        }

    </script>

app/views/entries/show.html.erb
<h1 style="color:blue; font-family:courier;"> <%= @entry.title %> </h1>


<p><%= @entry.body %></p>

<h4 style="color:blue; font-family:courier;">WORD COUNT: <%= @entry.body.split.size%><h4>

<%= link_to "Main Page", root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ljlite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>